package com.project.hdl.salesap.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.project.hdl.salesap.model.User;
import com.project.hdl.salesap.model.Task;
import com.project.hdl.salesap.model.ReportH;
import com.project.hdl.salesap.model.ReportD;

import com.project.hdl.salesap.model.UserDao;
import com.project.hdl.salesap.model.TaskDao;
import com.project.hdl.salesap.model.ReportHDao;
import com.project.hdl.salesap.model.ReportDDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig taskDaoConfig;
    private final DaoConfig reportHDaoConfig;
    private final DaoConfig reportDDaoConfig;

    private final UserDao userDao;
    private final TaskDao taskDao;
    private final ReportHDao reportHDao;
    private final ReportDDao reportDDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        reportHDaoConfig = daoConfigMap.get(ReportHDao.class).clone();
        reportHDaoConfig.initIdentityScope(type);

        reportDDaoConfig = daoConfigMap.get(ReportDDao.class).clone();
        reportDDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);
        reportHDao = new ReportHDao(reportHDaoConfig, this);
        reportDDao = new ReportDDao(reportDDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Task.class, taskDao);
        registerDao(ReportH.class, reportHDao);
        registerDao(ReportD.class, reportDDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        taskDaoConfig.clearIdentityScope();
        reportHDaoConfig.clearIdentityScope();
        reportDDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public ReportHDao getReportHDao() {
        return reportHDao;
    }

    public ReportDDao getReportDDao() {
        return reportDDao;
    }

}
