package com.project.hdl.salesap.model;

import org.greenrobot.greendao.annotation.*;

import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TR_REPORT_D".
 */
@Entity(nameInDb = "TR_REPORT_D")
public class ReportD {

    @SerializedName("uid_report_d")
    @Id
    @NotNull
    private String uid_report_d;
    @SerializedName("uid_report_h")
    private String uid_report_h;
    @SerializedName("product_name")
    private String product_name;
    @SerializedName("product_count")
    private String product_count;
    @SerializedName("product_price")
    private String product_price;

    @Generated
    public ReportD() {
    }

    public ReportD(String uid_report_d) {
        this.uid_report_d = uid_report_d;
    }

    @Generated
    public ReportD(String uid_report_d, String uid_report_h, String product_name, String product_count, String product_price) {
        this.uid_report_d = uid_report_d;
        this.uid_report_h = uid_report_h;
        this.product_name = product_name;
        this.product_count = product_count;
        this.product_price = product_price;
    }

    @NotNull
    public String getUid_report_d() {
        return uid_report_d;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUid_report_d(@NotNull String uid_report_d) {
        this.uid_report_d = uid_report_d;
    }

    public String getUid_report_h() {
        return uid_report_h;
    }

    public void setUid_report_h(String uid_report_h) {
        this.uid_report_h = uid_report_h;
    }

    public String getProduct_name() {
        return product_name;
    }

    public void setProduct_name(String product_name) {
        this.product_name = product_name;
    }

    public String getProduct_count() {
        return product_count;
    }

    public void setProduct_count(String product_count) {
        this.product_count = product_count;
    }

    public String getProduct_price() {
        return product_price;
    }

    public void setProduct_price(String product_price) {
        this.product_price = product_price;
    }

}
