package com.project.hdl.salesap.model;

import org.greenrobot.greendao.annotation.*;

import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TR_REPORT_H".
 */
@Entity(nameInDb = "TR_REPORT_H")
public class ReportH {

    @SerializedName("uid_report_h")
    @Id
    @NotNull
    private String uid_report_h;
    @SerializedName("uid_task")
    private String uid_task;
    @SerializedName("dtm_submit")
    private String dtm_submit;
    @SerializedName("total_price")
    private String total_price;
    @SerializedName("total_count")
    private String total_count;

    @Generated
    public ReportH() {
    }

    public ReportH(String uid_report_h) {
        this.uid_report_h = uid_report_h;
    }

    @Generated
    public ReportH(String uid_report_h, String uid_task, String dtm_submit, String total_price, String total_count) {
        this.uid_report_h = uid_report_h;
        this.uid_task = uid_task;
        this.dtm_submit = dtm_submit;
        this.total_price = total_price;
        this.total_count = total_count;
    }

    @NotNull
    public String getUid_report_h() {
        return uid_report_h;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUid_report_h(@NotNull String uid_report_h) {
        this.uid_report_h = uid_report_h;
    }

    public String getUid_task() {
        return uid_task;
    }

    public void setUid_task(String uid_task) {
        this.uid_task = uid_task;
    }

    public String getDtm_submit() {
        return dtm_submit;
    }

    public void setDtm_submit(String dtm_submit) {
        this.dtm_submit = dtm_submit;
    }

    public String getTotal_price() {
        return total_price;
    }

    public void setTotal_price(String total_price) {
        this.total_price = total_price;
    }

    public String getTotal_count() {
        return total_count;
    }

    public void setTotal_count(String total_count) {
        this.total_count = total_count;
    }

}
