package com.project.hdl.salesap.model;

import org.greenrobot.greendao.annotation.*;

import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TR_TASK".
 */
@Entity(nameInDb = "TR_TASK")
public class Task {

    @SerializedName("uid_task")
    @Id
    @NotNull
    private String uid_task;
    @SerializedName("login_id")
    private String login_id;
    @SerializedName("cust_name")
    private String cust_name;
    @SerializedName("dest_address")
    private String dest_address;
    @SerializedName("dtm_assign")
    private String dtm_assign;
    @SerializedName("lon")
    private String lon;
    @SerializedName("lat")
    private String lat;
    @SerializedName("phone_numb")
    private String phone_numb;
    @SerializedName("status")
    private String status;
    @SerializedName("dtm_upd")
    private java.util.Date dtm_upd;
    @SerializedName("dtm_assign_tmp")
    private java.util.Date dtm_assign_tmp;

    @Generated
    public Task() {
    }

    public Task(String uid_task) {
        this.uid_task = uid_task;
    }

    @Generated
    public Task(String uid_task, String login_id, String cust_name, String dest_address, String dtm_assign, String lon, String lat, String phone_numb, String status, java.util.Date dtm_upd, java.util.Date dtm_assign_tmp) {
        this.uid_task = uid_task;
        this.login_id = login_id;
        this.cust_name = cust_name;
        this.dest_address = dest_address;
        this.dtm_assign = dtm_assign;
        this.lon = lon;
        this.lat = lat;
        this.phone_numb = phone_numb;
        this.status = status;
        this.dtm_upd = dtm_upd;
        this.dtm_assign_tmp = dtm_assign_tmp;
    }

    @NotNull
    public String getUid_task() {
        return uid_task;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUid_task(@NotNull String uid_task) {
        this.uid_task = uid_task;
    }

    public String getLogin_id() {
        return login_id;
    }

    public void setLogin_id(String login_id) {
        this.login_id = login_id;
    }

    public String getCust_name() {
        return cust_name;
    }

    public void setCust_name(String cust_name) {
        this.cust_name = cust_name;
    }

    public String getDest_address() {
        return dest_address;
    }

    public void setDest_address(String dest_address) {
        this.dest_address = dest_address;
    }

    public String getDtm_assign() {
        return dtm_assign;
    }

    public void setDtm_assign(String dtm_assign) {
        this.dtm_assign = dtm_assign;
    }

    public String getLon() {
        return lon;
    }

    public void setLon(String lon) {
        this.lon = lon;
    }

    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public String getPhone_numb() {
        return phone_numb;
    }

    public void setPhone_numb(String phone_numb) {
        this.phone_numb = phone_numb;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public java.util.Date getDtm_upd() {
        return dtm_upd;
    }

    public void setDtm_upd(java.util.Date dtm_upd) {
        this.dtm_upd = dtm_upd;
    }

    public java.util.Date getDtm_assign_tmp() {
        return dtm_assign_tmp;
    }

    public void setDtm_assign_tmp(java.util.Date dtm_assign_tmp) {
        this.dtm_assign_tmp = dtm_assign_tmp;
    }

}
