package com.project.hdl.salesap.model;

import org.greenrobot.greendao.annotation.*;

import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "AM_USER".
 */
@Entity(nameInDb = "AM_USER")
public class User {

    @SerializedName("login_id")
    @Id
    @NotNull
    private String login_id;
    @SerializedName("job")
    private String job;
    @SerializedName("office")
    private String office;
    @SerializedName("branch")
    private String branch;
    @SerializedName("target")
    private String target;
    @SerializedName("current_gain")
    private String current_gain;
    @SerializedName("full_name")
    private String full_name;

    @Generated
    public User() {
    }

    public User(String login_id) {
        this.login_id = login_id;
    }

    @Generated
    public User(String login_id, String job, String office, String branch, String target, String current_gain, String full_name) {
        this.login_id = login_id;
        this.job = job;
        this.office = office;
        this.branch = branch;
        this.target = target;
        this.current_gain = current_gain;
        this.full_name = full_name;
    }

    @NotNull
    public String getLogin_id() {
        return login_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLogin_id(@NotNull String login_id) {
        this.login_id = login_id;
    }

    public String getJob() {
        return job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public String getOffice() {
        return office;
    }

    public void setOffice(String office) {
        this.office = office;
    }

    public String getBranch() {
        return branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

    public String getTarget() {
        return target;
    }

    public void setTarget(String target) {
        this.target = target;
    }

    public String getCurrent_gain() {
        return current_gain;
    }

    public void setCurrent_gain(String current_gain) {
        this.current_gain = current_gain;
    }

    public String getFull_name() {
        return full_name;
    }

    public void setFull_name(String full_name) {
        this.full_name = full_name;
    }

}
